name: 'tasty_bytes'
version: "2.0"
config-version: 2
profile: tasty_bytes

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]


## Target
target-path: target
clean-targets: [target, dbt_modules]

seeds:
  tasty_bytes:
    parameters:
      +schema: parameters
      +column_types:
        parameter_name: varchar(200)
        parameter_value: varchar(200)

## Models
models:
  tasty_bytes:
    staging:
      +materialized: table
    marts:
      +materialized: view
tests:
  +store_failures: true
  +severity: warn
on-run-start:
  - "{{ create_dq_tables()}}"
on-run-end:
  - "{{ dqstats_log_results(results)}}"
